### ISSUE TITLE
Error in Display

### ISSUE THREAD

**Issue by raza2022** [umair-khanzada/angularClock#1]
Hi @umair-khanzada I just followed the basic instruction. but the index page not working, here is the error log
`XMLHttpRequest cannot load file:///C:/Users/Abdul%20Hameed/Desktop/angularClock/clock.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

**Comment by umair-khanzada** [comment]
@raza2022 It is due to browser's `same origin policy` security restrictions.
But don't worry it is fixed.
